// Media Import Service for AI Chat
// Handles image/video import and processing for AI assistance
// 
// Features:
// - Image picker integration (camera + gallery)
// - Text extraction from images (OCR) using Google ML Kit
// - Image description generation
// - Video frame extraction for analysis
// - Support for multiple image formats

import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:image_picker/image_picker.dart';
import 'package:google_mlkit_text_recognition/google_mlkit_text_recognition.dart';
import 'hybrid_polie/translation_service.dart';

/// Provider for media import service
final mediaImportServiceProvider = Provider<MediaImportService>((ref) {
  return MediaImportService();
});

/// Result of media import and processing
class MediaImportResult {
  /// The imported file
  final File? file;
  
  /// Path to the imported file
  final String? filePath;
  
  /// Extracted text from image (if OCR was performed)
  final String? extractedText;
  
  /// Detected language of extracted text
  final String? detectedLanguage;
  
  /// Translation of extracted text (if requested)
  final String? translatedText;
  
  /// Image description generated by AI
  final String? imageDescription;
  
  /// Type of media imported
  final MediaType mediaType;
  
  /// Whether processing was successful
  final bool success;
  
  /// Error message if processing failed
  final String? error;
  
  /// Processing time in milliseconds
  final int processingTimeMs;

  MediaImportResult({
    this.file,
    this.filePath,
    this.extractedText,
    this.detectedLanguage,
    this.translatedText,
    this.imageDescription,
    this.mediaType = MediaType.image,
    this.success = false,
    this.error,
    this.processingTimeMs = 0,
  });

  bool get hasText => extractedText != null && extractedText!.isNotEmpty;
  bool get hasTranslation => translatedText != null && translatedText!.isNotEmpty;
}

/// Type of media being imported
enum MediaType {
  image,
  video,
  document,
}

/// Source for media import
enum MediaSource {
  camera,
  gallery,
}

/// Service for importing and processing media for AI chat
class MediaImportService {
  final ImagePicker _imagePicker = ImagePicker();
  final TranslationService _translationService = TranslationService();
  TextRecognizer? _textRecognizer;
  
  /// Initialize the text recognizer
  void _initTextRecognizer() {
    _textRecognizer ??= TextRecognizer(script: TextRecognitionScript.latin);
  }
  
  /// Dispose of resources
  void dispose() {
    _textRecognizer?.close();
  }
  
  /// Pick an image from camera or gallery
  Future<MediaImportResult> pickImage({
    required MediaSource source,
    bool performOCR = true,
    String? translateTo,
    int imageQuality = 85,
    double? maxWidth,
    double? maxHeight,
  }) async {
    final startTime = DateTime.now();
    
    try {
      final XFile? pickedFile = await _imagePicker.pickImage(
        source: source == MediaSource.camera 
            ? ImageSource.camera 
            : ImageSource.gallery,
        imageQuality: imageQuality,
        maxWidth: maxWidth ?? 1920,
        maxHeight: maxHeight ?? 1080,
      );
      
      if (pickedFile == null) {
        return MediaImportResult(
          error: 'No image selected',
          processingTimeMs: DateTime.now().difference(startTime).inMilliseconds,
        );
      }
      
      final file = File(pickedFile.path);
      
      // Perform OCR if requested
      String? extractedText;
      String? detectedLanguage;
      String? translatedText;
      
      if (performOCR) {
        final ocrResult = await extractTextFromImage(file);
        extractedText = ocrResult['text'];
        detectedLanguage = ocrResult['language'];
        
        // Translate if requested and text was extracted
        if (translateTo != null && extractedText != null && extractedText.isNotEmpty) {
          try {
            final translation = await _translationService.translate(
              text: extractedText,
              sourceLang: detectedLanguage ?? 'english',
              targetLang: translateTo,
            );
            translatedText = translation.translation;
          } catch (e) {
            debugPrint('Translation failed: $e');
          }
        }
      }
      
      return MediaImportResult(
        file: file,
        filePath: pickedFile.path,
        extractedText: extractedText,
        detectedLanguage: detectedLanguage,
        translatedText: translatedText,
        mediaType: MediaType.image,
        success: true,
        processingTimeMs: DateTime.now().difference(startTime).inMilliseconds,
      );
    } catch (e) {
      debugPrint('Error picking image: $e');
      return MediaImportResult(
        error: 'Failed to pick image: ${e.toString()}',
        processingTimeMs: DateTime.now().difference(startTime).inMilliseconds,
      );
    }
  }
  
  /// Extract text from an image using ML Kit OCR
  Future<Map<String, String?>> extractTextFromImage(File imageFile) async {
    _initTextRecognizer();
    
    try {
      final inputImage = InputImage.fromFile(imageFile);
      final recognizedText = await _textRecognizer!.processImage(inputImage);
      
      final text = recognizedText.text;
      
      // Detect language based on text characteristics
      String? detectedLanguage = _detectLanguage(text);
      
      return {
        'text': text,
        'language': detectedLanguage,
      };
    } catch (e) {
      debugPrint('OCR failed: $e');
      return {
        'text': null,
        'language': null,
      };
    }
  }
  
  /// Detect language from text based on character patterns
  String _detectLanguage(String text) {
    if (text.isEmpty) return 'unknown';
    
    // Check for specific character sets
    final hasAmharic = RegExp(r'[\u1200-\u137F]').hasMatch(text); // Ethiopic
    final hasArabic = RegExp(r'[\u0600-\u06FF]').hasMatch(text);
    final hasCJK = RegExp(r'[\u4E00-\u9FFF]').hasMatch(text);
    final hasDevanagari = RegExp(r'[\u0900-\u097F]').hasMatch(text);
    
    if (hasAmharic) return 'amharic';
    if (hasArabic) return 'arabic';
    if (hasCJK) return 'chinese';
    if (hasDevanagari) return 'hindi';
    
    // Check for Yoruba diacritics
    final hasYorubaDiacritics = RegExp(r'[ẹọṣẸỌṢ]').hasMatch(text);
    if (hasYorubaDiacritics) return 'yoruba';
    
    // Check for common language keywords
    final lowerText = text.toLowerCase();
    
    // Swahili common words
    if (lowerText.contains('na ') || lowerText.contains('wa ') || 
        lowerText.contains('ya ') || lowerText.contains('ni ')) {
      return 'swahili';
    }
    
    // Hausa common words
    if (lowerText.contains(' da ') || lowerText.contains(' ne ') ||
        lowerText.contains(' ta ')) {
      return 'hausa';
    }
    
    // French common words
    if (lowerText.contains(' le ') || lowerText.contains(' la ') ||
        lowerText.contains(' les ') || lowerText.contains(' un ')) {
      return 'french';
    }
    
    // Default to English for Latin script
    return 'english';
  }
  
  /// Pick multiple images
  Future<List<MediaImportResult>> pickMultipleImages({
    bool performOCR = true,
    String? translateTo,
    int imageQuality = 85,
    int limit = 5,
  }) async {
    try {
      final List<XFile> pickedFiles = await _imagePicker.pickMultiImage(
        imageQuality: imageQuality,
        limit: limit,
      );
      
      if (pickedFiles.isEmpty) {
        return [];
      }
      
      final results = <MediaImportResult>[];
      
      for (final pickedFile in pickedFiles) {
        final file = File(pickedFile.path);
        String? extractedText;
        String? detectedLanguage;
        String? translatedText;
        
        if (performOCR) {
          final ocrResult = await extractTextFromImage(file);
          extractedText = ocrResult['text'];
          detectedLanguage = ocrResult['language'];
          
          if (translateTo != null && extractedText != null && extractedText.isNotEmpty) {
            try {
              final translation = await _translationService.translate(
                text: extractedText,
                sourceLang: detectedLanguage ?? 'english',
                targetLang: translateTo,
              );
              translatedText = translation.translation;
            } catch (e) {
              debugPrint('Translation failed: $e');
            }
          }
        }
        
        results.add(MediaImportResult(
          file: file,
          filePath: pickedFile.path,
          extractedText: extractedText,
          detectedLanguage: detectedLanguage,
          translatedText: translatedText,
          mediaType: MediaType.image,
          success: true,
        ));
      }
      
      return results;
    } catch (e) {
      debugPrint('Error picking multiple images: $e');
      return [];
    }
  }
  
  /// Pick a video from camera or gallery
  Future<MediaImportResult> pickVideo({
    required MediaSource source,
    Duration? maxDuration,
  }) async {
    final startTime = DateTime.now();
    
    try {
      final XFile? pickedFile = await _imagePicker.pickVideo(
        source: source == MediaSource.camera 
            ? ImageSource.camera 
            : ImageSource.gallery,
        maxDuration: maxDuration ?? const Duration(minutes: 5),
      );
      
      if (pickedFile == null) {
        return MediaImportResult(
          error: 'No video selected',
          processingTimeMs: DateTime.now().difference(startTime).inMilliseconds,
        );
      }
      
      final file = File(pickedFile.path);
      
      return MediaImportResult(
        file: file,
        filePath: pickedFile.path,
        mediaType: MediaType.video,
        success: true,
        processingTimeMs: DateTime.now().difference(startTime).inMilliseconds,
      );
    } catch (e) {
      debugPrint('Error picking video: $e');
      return MediaImportResult(
        error: 'Failed to pick video: ${e.toString()}',
        processingTimeMs: DateTime.now().difference(startTime).inMilliseconds,
      );
    }
  }
  
  /// Build a prompt for AI chat based on media import result
  String buildAIPrompt(MediaImportResult result, {String? userQuestion}) {
    final buffer = StringBuffer();
    
    if (result.hasText) {
      buffer.writeln('I have an image with the following text:');
      buffer.writeln('---');
      buffer.writeln(result.extractedText);
      buffer.writeln('---');
      
      if (result.detectedLanguage != null) {
        buffer.writeln('Detected language: ${result.detectedLanguage}');
      }
      
      if (result.hasTranslation) {
        buffer.writeln('\nTranslation:');
        buffer.writeln(result.translatedText);
      }
    } else {
      buffer.writeln('I have uploaded an image.');
    }
    
    if (userQuestion != null && userQuestion.isNotEmpty) {
      buffer.writeln('\nMy question: $userQuestion');
    } else {
      buffer.writeln('\nPlease help me understand this content or translate it.');
    }
    
    return buffer.toString();
  }
  
  /// Get supported image formats
  static List<String> get supportedImageFormats => [
    'jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp',
  ];
  
  /// Get supported video formats
  static List<String> get supportedVideoFormats => [
    'mp4', 'mov', 'avi', 'webm', '3gp',
  ];
  
  /// Check if a file extension is supported
  static bool isSupported(String extension, MediaType type) {
    final ext = extension.toLowerCase().replaceAll('.', '');
    switch (type) {
      case MediaType.image:
        return supportedImageFormats.contains(ext);
      case MediaType.video:
        return supportedVideoFormats.contains(ext);
      case MediaType.document:
        return ['pdf', 'doc', 'docx', 'txt'].contains(ext);
    }
  }
}
