/// Badge rarity levels
enum BadgeRarity {
  common,
  uncommon,
  rare,
  epic,
  legendary,
}

/// Badge categories
enum BadgeCategory {
  streak,
  learning,
  pronunciation,
  cultural,
  social,
  special,
  languageSpecific,
}

/// Comprehensive badge model with African cultural context
class Badge {
  final String id;
  final String name;
  final String description;
  final BadgeRarity rarity;
  final BadgeCategory category;
  final String icon; // Emoji or icon identifier
  final int xpReward;
  final int cowriesReward;
  final int beadsReward;
  final String? language; // Language-specific badges
  final Map<String, dynamic>? requirements; // Flexible requirements
  final bool isUnlocked;
  final DateTime? unlockedAt;

  Badge({
    required this.id,
    required this.name,
    required this.description,
    required this.rarity,
    required this.category,
    required this.icon,
    this.xpReward = 50,
    this.cowriesReward = 0,
    this.beadsReward = 0,
    this.language,
    this.requirements,
    this.isUnlocked = false,
    this.unlockedAt,
  });

  Badge copyWith({
    String? id,
    String? name,
    String? description,
    BadgeRarity? rarity,
    BadgeCategory? category,
    String? icon,
    int? xpReward,
    int? cowriesReward,
    int? beadsReward,
    String? language,
    Map<String, dynamic>? requirements,
    bool? isUnlocked,
    DateTime? unlockedAt,
  }) {
    return Badge(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      rarity: rarity ?? this.rarity,
      category: category ?? this.category,
      icon: icon ?? this.icon,
      xpReward: xpReward ?? this.xpReward,
      cowriesReward: cowriesReward ?? this.cowriesReward,
      beadsReward: beadsReward ?? this.beadsReward,
      language: language ?? this.language,
      requirements: requirements ?? this.requirements,
      isUnlocked: isUnlocked ?? this.isUnlocked,
      unlockedAt: unlockedAt ?? this.unlockedAt,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'description': description,
        'rarity': rarity.name,
        'category': category.name,
        'icon': icon,
        'xpReward': xpReward,
        'cowriesReward': cowriesReward,
        'beadsReward': beadsReward,
        'language': language,
        'requirements': requirements,
        'isUnlocked': isUnlocked,
        'unlockedAt': unlockedAt?.toIso8601String(),
      };

  factory Badge.fromJson(Map<String, dynamic> json) => Badge(
        id: (json['id'] as String?) ?? '',
        name: (json['name'] as String?) ?? '',
        description: (json['description'] as String?) ?? '',
        rarity: BadgeRarity.values.firstWhere(
          (e) => e.name == (json['rarity'] as String?),
          orElse: () => BadgeRarity.common,
        ),
        category: BadgeCategory.values.firstWhere(
          (e) => e.name == (json['category'] as String?),
          orElse: () => BadgeCategory.learning,
        ),
        icon: (json['icon'] as String?) ?? '',
        xpReward: (json['xpReward'] as num?)?.toInt() ?? 50,
        cowriesReward: (json['cowriesReward'] as num?)?.toInt() ?? 0,
        beadsReward: (json['beadsReward'] as num?)?.toInt() ?? 0,
        language: json['language'] as String?,
        requirements: json['requirements'] is Map
            ? Map<String, dynamic>.from(json['requirements'] as Map)
            : null,
        isUnlocked: json['isUnlocked'] as bool? ?? false,
        unlockedAt: json['unlockedAt'] != null
            ? DateTime.tryParse((json['unlockedAt'] as String?) ?? '')
            : null,
      );
}

/// Predefined African-themed badges
class BadgeDefinitions {
  static List<Badge> getAllBadges() {
    return [
      // ========== LEARNING BADGES ==========
      Badge(
        id: 'first_lesson',
        name: 'First Lesson',
        description: 'Complete your first lesson',
        rarity: BadgeRarity.common,
        category: BadgeCategory.learning,
        icon: '🎓',
        xpReward: 50,
        cowriesReward: 25,
      ),
      Badge(
        id: 'quick_learner',
        name: 'Quick Learner',
        description: 'Complete 5 lessons in one day',
        rarity: BadgeRarity.uncommon,
        category: BadgeCategory.learning,
        icon: '⚡',
        xpReward: 150,
        cowriesReward: 75,
      ),
      Badge(
        id: 'marathon_learner',
        name: 'Marathon Learner',
        description: 'Complete 10 lessons in one day',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.learning,
        icon: '🏃',
        xpReward: 500,
        cowriesReward: 250,
      ),
      Badge(
        id: 'polyglot_starter',
        name: 'Polyglot Starter',
        description: 'Start learning 2 languages',
        rarity: BadgeRarity.uncommon,
        category: BadgeCategory.learning,
        icon: '🌍',
        xpReward: 200,
        cowriesReward: 100,
      ),
      Badge(
        id: 'polyglot_master',
        name: 'Polyglot Master',
        description: 'Learn 5+ languages',
        rarity: BadgeRarity.legendary,
        category: BadgeCategory.learning,
        icon: '🌐',
        xpReward: 2000,
        cowriesReward: 1000,
        beadsReward: 15,
      ),
      Badge(
        id: 'grammar_guru',
        name: 'Grammar Guru',
        description: 'Complete all grammar exercises in a unit',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.learning,
        icon: '📚',
        xpReward: 400,
        cowriesReward: 200,
      ),
      Badge(
        id: 'vocabulary_vault',
        name: 'Vocabulary Vault',
        description: 'Learn 500 words',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.learning,
        icon: '📖',
        xpReward: 600,
        cowriesReward: 300,
      ),
      Badge(
        id: 'word_wizard',
        name: 'Word Wizard',
        description: 'Learn 1000 words',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.learning,
        icon: '✨',
        xpReward: 1500,
        cowriesReward: 750,
        beadsReward: 10,
      ),
      Badge(
        id: 'pronunciation_pro',
        name: 'Pronunciation Pro',
        description: 'Score 90%+ on 10 pronunciation exercises',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.pronunciation,
        icon: '🎤',
        xpReward: 500,
        cowriesReward: 250,
      ),

      // ========== STREAK BADGES ==========
      Badge(
        id: 'streak_7',
        name: 'Hot Streak',
        description: 'Maintain a 7-day learning streak',
        rarity: BadgeRarity.uncommon,
        category: BadgeCategory.streak,
        icon: '🔥',
        xpReward: 100,
        cowriesReward: 50,
      ),
      Badge(
        id: 'streak_30',
        name: 'On Fire',
        description: 'Maintain a 30-day learning streak',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.streak,
        icon: '⭐',
        xpReward: 500,
        cowriesReward: 200,
      ),
      Badge(
        id: 'streak_100',
        name: 'Unstoppable',
        description: 'Maintain a 100-day learning streak',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.streak,
        icon: '💪',
        xpReward: 1500,
        cowriesReward: 750,
        beadsReward: 10,
      ),
      Badge(
        id: 'streak_365',
        name: 'Legendary',
        description: 'Maintain a 365-day learning streak',
        rarity: BadgeRarity.legendary,
        category: BadgeCategory.streak,
        icon: '👑',
        xpReward: 5000,
        cowriesReward: 2500,
        beadsReward: 25,
      ),
      Badge(
        id: 'early_bird',
        name: 'Early Bird',
        description: 'Practice before 8 AM, 7 times',
        rarity: BadgeRarity.uncommon,
        category: BadgeCategory.streak,
        icon: '🌅',
        xpReward: 200,
        cowriesReward: 100,
      ),
      Badge(
        id: 'night_owl',
        name: 'Night Owl',
        description: 'Practice after 10 PM, 7 times',
        rarity: BadgeRarity.uncommon,
        category: BadgeCategory.streak,
        icon: '🦉',
        xpReward: 200,
        cowriesReward: 100,
      ),
      Badge(
        id: 'weekend_warrior',
        name: 'Weekend Warrior',
        description: 'Practice every weekend for a month',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.streak,
        icon: '🏋️',
        xpReward: 400,
        cowriesReward: 200,
      ),
      Badge(
        id: 'harmattan_survivor',
        name: 'Harmattan Survivor',
        description: '90-day streak during dry season (Dec-Feb)',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.streak,
        icon: '🌬️',
        xpReward: 1500,
        cowriesReward: 500,
        beadsReward: 5,
      ),

      // ========== SOCIAL BADGES ==========
      Badge(
        id: 'social_butterfly',
        name: 'Social Butterfly',
        description: 'Add 10 friends',
        rarity: BadgeRarity.uncommon,
        category: BadgeCategory.social,
        icon: '🦋',
        xpReward: 300,
        cowriesReward: 150,
      ),
      Badge(
        id: 'generous_soul',
        name: 'Generous Soul',
        description: 'Send 10 gifts',
        rarity: BadgeRarity.uncommon,
        category: BadgeCategory.social,
        icon: '🎁',
        xpReward: 250,
        cowriesReward: 125,
      ),
      Badge(
        id: 'team_player',
        name: 'Team Player',
        description: 'Complete 5 friend quests',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.social,
        icon: '🤝',
        xpReward: 500,
        cowriesReward: 250,
      ),
      Badge(
        id: 'community_leader',
        name: 'Community Leader',
        description: 'Get 50 likes in community',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.social,
        icon: '👑',
        xpReward: 600,
        cowriesReward: 300,
      ),
      Badge(
        id: 'mentor',
        name: 'Mentor',
        description: 'Help 10 users in chat',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.social,
        icon: '🧑‍🏫',
        xpReward: 500,
        cowriesReward: 250,
      ),
      Badge(
        id: 'tribe_chief',
        name: 'Tribe Chief',
        description: 'Lead a tribe to top 3 in leaderboard',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.social,
        icon: '🏆',
        xpReward: 1500,
        cowriesReward: 750,
        beadsReward: 10,
      ),
      Badge(
        id: 'ubuntu_helper',
        name: 'Ubuntu Helper',
        description: 'Help 50 other learners in forums',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.social,
        icon: '🤝',
        xpReward: 1000,
        cowriesReward: 500,
        beadsReward: 5,
      ),

      // ========== ACHIEVEMENT BADGES ==========
      Badge(
        id: 'speed_demon',
        name: 'Speed Demon',
        description: 'Complete a lesson in under 2 minutes',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.learning,
        icon: '⚡',
        xpReward: 300,
        cowriesReward: 150,
      ),
      Badge(
        id: 'perfectionist',
        name: 'Perfectionist',
        description: 'Get 100% on 10 lessons',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.learning,
        icon: '💯',
        xpReward: 1000,
        cowriesReward: 500,
        beadsReward: 5,
      ),
      Badge(
        id: 'perfect_week',
        name: 'Perfect Week',
        description: 'No mistakes for 7 days',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.learning,
        icon: '🌟',
        xpReward: 1200,
        cowriesReward: 600,
        beadsReward: 8,
      ),
      Badge(
        id: 'level_10',
        name: 'Level 10 Achiever',
        description: 'Reach level 10',
        rarity: BadgeRarity.uncommon,
        category: BadgeCategory.learning,
        icon: '🔟',
        xpReward: 300,
        cowriesReward: 150,
      ),
      Badge(
        id: 'level_25',
        name: 'Level 25 Master',
        description: 'Reach level 25',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.learning,
        icon: '2️⃣5️⃣',
        xpReward: 800,
        cowriesReward: 400,
      ),
      Badge(
        id: 'level_50',
        name: 'Level 50 Champion',
        description: 'Reach level 50',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.learning,
        icon: '5️⃣0️⃣',
        xpReward: 2000,
        cowriesReward: 1000,
        beadsReward: 15,
      ),
      Badge(
        id: 'level_100',
        name: 'Level 100 Legend',
        description: 'Reach level 100',
        rarity: BadgeRarity.legendary,
        category: BadgeCategory.learning,
        icon: '💯',
        xpReward: 5000,
        cowriesReward: 2500,
        beadsReward: 30,
      ),
      Badge(
        id: 'cowries_collector',
        name: 'Cowries Collector',
        description: 'Earn 1000 Cowries',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.learning,
        icon: '🐚',
        xpReward: 500,
        cowriesReward: 250,
      ),
      Badge(
        id: 'ngwenya_hunter',
        name: 'Ngwenya Hunter',
        description: 'Earn 100 Ngwenya',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.learning,
        icon: '🦎',
        xpReward: 600,
        cowriesReward: 300,
      ),
      Badge(
        id: 'crown_collector',
        name: 'Crown Collector',
        description: 'Earn 10 crowns',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.learning,
        icon: '👑',
        xpReward: 1500,
        cowriesReward: 750,
        beadsReward: 10,
      ),
      Badge(
        id: 'explorer',
        name: 'Explorer',
        description: 'Visit every section of the app',
        rarity: BadgeRarity.uncommon,
        category: BadgeCategory.learning,
        icon: '🗺️',
        xpReward: 200,
        cowriesReward: 100,
      ),

      // ========== CULTURAL BADGES ==========
      Badge(
        id: 'ubuntu_spirit',
        name: 'Ubuntu Spirit',
        description: 'Complete Ubuntu mode challenges',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.cultural,
        icon: '❤️',
        xpReward: 600,
        cowriesReward: 300,
      ),
      Badge(
        id: 'cultural_explorer',
        name: 'Cultural Explorer',
        description: 'Read 10 culture magazine articles',
        rarity: BadgeRarity.uncommon,
        category: BadgeCategory.cultural,
        icon: '📰',
        xpReward: 300,
        cowriesReward: 150,
      ),
      Badge(
        id: 'proverb_master',
        name: 'Proverb Master',
        description: 'Learn 50 African proverbs',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.cultural,
        icon: '💬',
        xpReward: 1500,
        cowriesReward: 750,
        beadsReward: 10,
      ),
      Badge(
        id: 'storyteller',
        name: 'Storyteller',
        description: 'Complete 20 story lessons',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.cultural,
        icon: '📖',
        xpReward: 800,
        cowriesReward: 400,
      ),
      Badge(
        id: 'rhythm_master',
        name: 'Rhythm Master',
        description: 'Complete all drum rhythm challenges',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.cultural,
        icon: '🥁',
        xpReward: 1200,
        cowriesReward: 600,
        beadsReward: 8,
      ),
      Badge(
        id: 'jollof_wars_victor',
        name: 'Jollof Wars Victor',
        description: 'Win 10 food-ordering roleplays',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.cultural,
        icon: '🍛',
        xpReward: 500,
        cowriesReward: 200,
      ),
      Badge(
        id: 'adinkra_sage',
        name: 'Adinkra Sage',
        description: 'Collect all 30 wisdom-symbol lessons',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.cultural,
        icon: '🕉️',
        xpReward: 1500,
        cowriesReward: 500,
        beadsReward: 10,
      ),
      Badge(
        id: 'market_bargainer',
        name: 'Market Bargainer',
        description: 'Successfully complete 20 market bargaining roleplays',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.cultural,
        icon: '🏪',
        xpReward: 600,
        cowriesReward: 250,
      ),
      Badge(
        id: 'fufu_champion',
        name: 'Fufu Champion',
        description: 'Master all food vocabulary in 5 languages',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.cultural,
        icon: '🍽️',
        xpReward: 1200,
        cowriesReward: 400,
        beadsReward: 5,
      ),

      // ========== PRONUNCIATION BADGES ==========
      Badge(
        id: 'click_master',
        name: 'Click Master',
        description: '1000 perfect Xhosa/Zulu clicks',
        rarity: BadgeRarity.legendary,
        category: BadgeCategory.pronunciation,
        icon: '👆',
        xpReward: 2000,
        cowriesReward: 1000,
        beadsReward: 15,
        language: 'xhosa',
      ),
      Badge(
        id: 'tonal_master',
        name: 'Tonal Master',
        description: '7 days of perfect tonal pronunciation',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.pronunciation,
        icon: '🎵',
        xpReward: 1000,
        cowriesReward: 300,
        beadsReward: 3,
      ),

      // ========== SEASONAL/SPECIAL BADGES ==========
      Badge(
        id: 'beta_tester',
        name: 'Beta Tester',
        description: 'Participate in beta testing',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.special,
        icon: '🧪',
        xpReward: 500,
        cowriesReward: 250,
      ),
      Badge(
        id: 'founding_member',
        name: 'Founding Member',
        description: 'Join during the first month',
        rarity: BadgeRarity.legendary,
        category: BadgeCategory.special,
        icon: '⭐',
        xpReward: 2000,
        cowriesReward: 1000,
        beadsReward: 20,
      ),
      Badge(
        id: 'holiday_learner',
        name: 'Holiday Learner',
        description: 'Practice on a holiday',
        rarity: BadgeRarity.uncommon,
        category: BadgeCategory.special,
        icon: '🎉',
        xpReward: 200,
        cowriesReward: 100,
      ),
      Badge(
        id: 'new_year_resolve',
        name: 'New Year Resolve',
        description: 'Practice on Jan 1',
        rarity: BadgeRarity.uncommon,
        category: BadgeCategory.special,
        icon: '🎊',
        xpReward: 250,
        cowriesReward: 125,
      ),
      Badge(
        id: 'night_runner',
        name: 'Night Runner',
        description: 'Complete lessons 12am-4am 50 times',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.special,
        icon: '🌙',
        xpReward: 800,
        cowriesReward: 300,
      ),

      // ========== LANGUAGE-SPECIFIC BADGES ==========
      Badge(
        id: 'yoruba_oracle',
        name: 'Yoruba Oracle',
        description: 'Master 500 Yoruba words with perfect diacritics',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.languageSpecific,
        icon: '🔮',
        xpReward: 1500,
        cowriesReward: 500,
        beadsReward: 10,
        language: 'yoruba',
      ),
      Badge(
        id: 'swahili_coast_explorer',
        name: 'Swahili Coast Explorer',
        description: 'Complete all Swahili coastal scenarios',
        rarity: BadgeRarity.rare,
        category: BadgeCategory.languageSpecific,
        icon: '🏖️',
        xpReward: 800,
        cowriesReward: 300,
        language: 'swahili',
      ),
      Badge(
        id: 'zulu_warrior',
        name: 'Zulu Warrior',
        description: 'Achieve 95%+ pronunciation on 100 Zulu phrases',
        rarity: BadgeRarity.epic,
        category: BadgeCategory.languageSpecific,
        icon: '🛡️',
        xpReward: 1200,
        cowriesReward: 400,
        beadsReward: 5,
        language: 'zulu',
      ),
    ];
  }

  static Badge? getBadgeById(String id) {
    try {
      return getAllBadges().firstWhere(
        (badge) => badge.id == id,
      );
    } catch (e) {
      return null;
    }
  }
}

