// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmrruENewwglxkBOwgFEULiriFXXrjcxo',
    appId: '1:202890241823:android:bb7801cf2cc6e5b878722a',
    messagingSenderId: '202890241823',
    projectId: 'lingafriq-mobile-app',
    storageBucket: 'lingafriq-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZVxzwn2sOmkdBcMMXGsmhuscp1w5CGCA',
    appId: '1:202890241823:ios:ae2190c00d638d7e78722a',
    messagingSenderId: '202890241823',
    projectId: 'lingafriq-mobile-app',
    storageBucket: 'lingafriq-mobile-app.appspot.com',
    iosClientId: '202890241823-6eb76rreah64ms60f18jjbm8j81j9lh6.apps.googleusercontent.com',
    iosBundleId: 'com.owlab.lingafriq',
  );
}
