import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:lingafriq/utils/utils.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:lingafriq/config/api_contract.dart';

Widget kImagePlaceHolder(_, __) {
  return const Padding(
    padding: EdgeInsets.all(50.0),
    child: Center(child: CupertinoActivityIndicator()),
  );
}

Widget kErrorWidget(_, __, ___) => const Padding(
      padding: EdgeInsets.all(50),
      child: Center(child: Icon(Icons.error_outline, color: Colors.red)),
    );

Widget kErrorLogoWidget(_, __, ___) => ColoredBox(
      color: Colors.black,
      child: Image.asset(Images.logo).p16(),
    );

kLaunchUrl(String url) async {
  final uri = Uri.parse(url);
  if (await canLaunchUrl(uri)) {
    try {
      final result = await launchUrl(uri);
      debugPrint(result.toString());
      if (!result) {
        await launchUrl(uri);
      }
    } catch (e) {
      debugPrint(e.toString());
    }
  } else {
    await launchUrl(uri);
  }
}

const kBorderRadius = 6.0;

final kGradientTextEffects = <Effect<dynamic>>[
  ScaleEffect(
    duration: 500.milliseconds,
    curve: Curves.fastLinearToSlowEaseIn,
  ),
  ShakeEffect(
    duration: 2000.milliseconds,
    delay: 500.milliseconds,
    curve: Curves.fastLinearToSlowEaseIn,
    hz: 5,
  ),
  // ShimmerEffect(
  //   delay: 250.milliseconds,
  // ),

  const MoveEffect(begin: Offset(0, -4)),
  for (var i = 1; i < 12; i++)
    ShakeEffect(
      duration: 1.seconds,
      delay: (i * 3).seconds,
      hz: 5,
    ),
  for (var i = 1; i < 12; i++)
    ShimmerEffect(
      duration: 1.seconds,
      delay: (i * 4).seconds,
    ),
];

Map<String, String> kCountries = {
  "Afghanistan": "🇦🇫",
  "Åland Islands": "🇦🇽",
  "Albania": "🇦🇱",
  "Algeria": "🇩🇿",
  "American Samoa": "🇦🇸",
  "Andorra": "🇦🇩",
  "Angola": "🇦🇴",
  "Anguilla": "🇦🇮",
  "Antarctica": "🇦🇶",
  "Antigua and Barbuda": "🇦🇬",
  "Argentina": "🇦🇷",
  "Armenia": "🇦🇲",
  "Aruba": "🇦🇼",
  "Australia": "🇦🇺",
  "Austria": "🇦🇹",
  "Azerbaijan": "🇦🇿",
  "Bahamas": "🇧🇸",
  "Bahrain": "🇧🇭",
  "Bangladesh": "🇧🇩",
  "Barbados": "🇧🇧",
  "Belarus": "🇧🇾",
  "Belgium": "🇧🇪",
  "Belize": "🇧🇿",
  "Benin": "🇧🇯",
  "Bermuda": "🇧🇲",
  "Bhutan": "🇧🇹",
  "Bolivia": "🇧🇴",
  "Bosnia and Herzegovina": "🇧🇦",
  "Botswana": "🇧🇼",
  "Bouvet Island": "🇧🇻",
  "Brazil": "🇧🇷",
  "British Indian Ocean Territory": "🇮🇴",
  "Brunei": "🇧🇳",
  "Bulgaria": "🇧🇬",
  "Burkina Faso": "🇧🇫",
  "Burundi": "🇧🇮",
  "Cambodia": "🇰🇭",
  "Cameroon": "🇨🇲",
  "Canada": "🇨🇦",
  "Cape Verde": "🇨🇻",
  "Caribbean Netherlands": "🇧🇶",
  "Cayman Islands": "🇰🇾",
  "Central African Republic": "🇨🇫",
  "Chad": "🇹🇩",
  "Chile": "🇨🇱",
  "China": "🇨🇳",
  "Christmas Island": "🇨🇽",
  "Cocos (Keeling) Islands": "🇨🇨",
  "Colombia": "🇨🇴",
  "Comoros": "🇰🇲",
  "Republic of the Congo": "🇨🇬",
  "DR Congo": "🇨🇩",
  "Cook Islands": "🇨🇰",
  "Costa Rica": "🇨🇷",
  "Côte d'Ivoire (Ivory Coast)": "🇨🇮",
  "Croatia": "🇭🇷",
  "Cuba": "🇨🇺",
  "Curaçao": "🇨🇼",
  "Cyprus": "🇨🇾",
  "Czechia": "🇨🇿",
  "Denmark": "🇩🇰",
  "Djibouti": "🇩🇯",
  "Dominica": "🇩🇲",
  "Dominican Republic": "🇩🇴",
  "Ecuador": "🇪🇨",
  "Egypt": "🇪🇬",
  "El Salvador": "🇸🇻",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Equatorial Guinea": "🇬🇶",
  "Eritrea": "🇪🇷",
  "Estonia": "🇪🇪",
  "Eswatini (Swaziland)": "🇸🇿",
  "Ethiopia": "🇪🇹",
  "Falkland Islands": "🇫🇰",
  "Faroe Islands": "🇫🇴",
  "Fiji": "🇫🇯",
  "Finland": "🇫🇮",
  "France": "🇫🇷",
  "French Guiana": "🇬🇫",
  "French Polynesia": "🇵🇫",
  "French Southern and Antarctic Lands": "🇹🇫",
  "Gabon": "🇬🇦",
  "Gambia": "🇬🇲",
  "Georgia": "🇬🇪",
  "Germany": "🇩🇪",
  "Ghana": "🇬🇭",
  "Gibraltar": "🇬🇮",
  "Greece": "🇬🇷",
  "Greenland": "🇬🇱",
  "Grenada": "🇬🇩",
  "Guadeloupe": "🇬🇵",
  "Guam": "🇬🇺",
  "Guatemala": "🇬🇹",
  "Guernsey": "🇬🇬",
  "Guinea": "🇬🇳",
  "Guinea-Bissau": "🇬🇼",
  "Guyana": "🇬🇾",
  "Haiti": "🇭🇹",
  "Heard Island and McDonald Islands": "🇭🇲",
  "Honduras": "🇭🇳",
  "Hong Kong": "🇭🇰",
  "Hungary": "🇭🇺",
  "Iceland": "🇮🇸",
  "India": "🇮🇳",
  "Indonesia": "🇮🇩",
  "Iran": "🇮🇷",
  "Iraq": "🇮🇶",
  "Ireland": "🇮🇪",
  "Isle of Man": "🇮🇲",
  "Israel": "🇮🇱",
  "Italy": "🇮🇹",
  "Jamaica": "🇯🇲",
  "Japan": "🇯🇵",
  "Jersey": "🇯🇪",
  "Jordan": "🇯🇴",
  "Kazakhstan": "🇰🇿",
  "Kenya": "🇰🇪",
  "Kiribati": "🇰🇮",
  "North Korea": "🇰🇵",
  "South Korea": "🇰🇷",
  "Kosovo": "🇽🇰",
  "Kuwait": "🇰🇼",
  "Kyrgyzstan": "🇰🇬",
  "Laos": "🇱🇦",
  "Latvia": "🇱🇻",
  "Lebanon": "🇱🇧",
  "Lesotho": "🇱🇸",
  "Liberia": "🇱🇷",
  "Libya": "🇱🇾",
  "Liechtenstein": "🇱🇮",
  "Lithuania": "🇱🇹",
  "Luxembourg": "🇱🇺",
  "Macau": "🇲🇴",
  "Madagascar": "🇲🇬",
  "Malawi": "🇲🇼",
  "Malaysia": "🇲🇾",
  "Maldives": "🇲🇻",
  "Mali": "🇲🇱",
  "Malta": "🇲🇹",
  "Marshall Islands": "🇲🇭",
  "Martinique": "🇲🇶",
  "Mauritania": "🇲🇷",
  "Mauritius": "🇲🇺",
  "Mayotte": "🇾🇹",
  "Mexico": "🇲🇽",
  "Micronesia": "🇫🇲",
  "Moldova": "🇲🇩",
  "Monaco": "🇲🇨",
  "Mongolia": "🇲🇳",
  "Montenegro": "🇲🇪",
  "Montserrat": "🇲🇸",
  "Morocco": "🇲🇦",
  "Mozambique": "🇲🇿",
  "Myanmar": "🇲🇲",
  "Namibia": "🇳🇦",
  "Nauru": "🇳🇷",
  "Nepal": "🇳🇵",
  "Netherlands": "🇳🇱",
  "New Caledonia": "🇳🇨",
  "New Zealand": "🇳🇿",
  "Nicaragua": "🇳🇮",
  "Niger": "🇳🇪",
  "Nigeria": "🇳🇬",
  "Niue": "🇳🇺",
  "Norfolk Island": "🇳🇫",
  "North Macedonia": "🇲🇰",
  "Northern Mariana Islands": "🇲🇵",
  "Norway": "🇳🇴",
  "Oman": "🇴🇲",
  "Pakistan": "🇵🇰",
  "Palau": "🇵🇼",
  "Palestine": "🇵🇸",
  "Panama": "🇵🇦",
  "Papua New Guinea": "🇵🇬",
  "Paraguay": "🇵🇾",
  "Peru": "🇵🇪",
  "Philippines": "🇵🇭",
  "Pitcairn Islands": "🇵🇳",
  "Poland": "🇵🇱",
  "Portugal": "🇵🇹",
  "Puerto Rico": "🇵🇷",
  "Qatar": "🇶🇦",
  "Réunion": "🇷🇪",
  "Romania": "🇷🇴",
  "Russia": "🇷🇺",
  "Rwanda": "🇷🇼",
  "Saint Barthélemy": "🇧🇱",
  "Saint Helena, Ascension and Tristan da Cunha": "🇸🇭",
  "Saint Kitts and Nevis": "🇰🇳",
  "Saint Lucia": "🇱🇨",
  "Saint Martin": "🇲🇫",
  "Saint Pierre and Miquelon": "🇵🇲",
  "Saint Vincent and the Grenadines": "🇻🇨",
  "Samoa": "🇼🇸",
  "San Marino": "🇸🇲",
  "São Tomé and Príncipe": "🇸🇹",
  "Saudi Arabia": "🇸🇦",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Senegal": "🇸🇳",
  "Serbia": "🇷🇸",
  "Seychelles": "🇸🇨",
  "Sierra Leone": "🇸🇱",
  "Singapore": "🇸🇬",
  "Sint Maarten": "🇸🇽",
  "Slovakia": "🇸🇰",
  "Slovenia": "🇸🇮",
  "Solomon Islands": "🇸🇧",
  "Somalia": "🇸🇴",
  "South Africa": "🇿🇦",
  "South Georgia": "🇬🇸",
  "South Sudan": "🇸🇸",
  "Spain": "🇪🇸",
  "Sri Lanka": "🇱🇰",
  "Sudan": "🇸🇩",
  "Suriname": "🇸🇷",
  "Svalbard and Jan Mayen": "🇸🇯",
  "Sweden": "🇸🇪",
  "Switzerland": "🇨🇭",
  "Syria": "🇸🇾",
  "Taiwan": "🇹🇼",
  "Tajikistan": "🇹🇯",
  "Tanzania": "🇹🇿",
  "Thailand": "🇹🇭",
  "Timor-Leste": "🇹🇱",
  "Togo": "🇹🇬",
  "Tokelau": "🇹🇰",
  "Tonga": "🇹🇴",
  "Trinidad and Tobago": "🇹🇹",
  "Tunisia": "🇹🇳",
  "Turkey": "🇹🇷",
  "Turkmenistan": "🇹🇲",
  "Turks and Caicos Islands": "🇹🇨",
  "Tuvalu": "🇹🇻",
  "Uganda": "🇺🇬",
  "Ukraine": "🇺🇦",
  "United Arab Emirates": "🇦🇪",
  "United Kingdom": "🇬🇧",
  "United States": "🇺🇸",
  "United States Minor Outlying Islands": "🇺🇲",
  "Uruguay": "🇺🇾",
  "Uzbekistan": "🇺🇿",
  "Vanuatu": "🇻🇺",
  "Vatican City (Holy See)": "🇻🇦",
  "Venezuela": "🇻🇪",
  "Vietnam": "🇻🇳",
  "British Virgin Islands": "🇻🇬",
  "United States Virgin Islands": "🇻🇮",
  "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Wallis and Futuna": "🇼🇫",
  "Western Sahara": "🇪🇭",
  "Yemen": "🇾🇪",
  "Zambia": "🇿🇲",
  "Zimbabwe": "🇿🇼",
};

final kAvatarsList = {
  ApiContract.url('${ApiContract.media.base}avatars/avatar_1.png'):
      "assets/images/avatar_1.png",
  ApiContract.url('${ApiContract.media.base}avatars/avatar_2.png'):
      "assets/images/avatar_2.png",
  ApiContract.url('${ApiContract.media.base}avatars/avatar_3.png'):
      "assets/images/avatar_3.png",
  ApiContract.url('${ApiContract.media.base}avatars/avatar_4.png'):
      "assets/images/avatar_4.png",
  ApiContract.url('${ApiContract.media.base}avatars/avatar_5.png'):
      "assets/images/avatar_5.png",
  ApiContract.url('${ApiContract.media.base}avatars/avatar_6.png'):
      "assets/images/avatar_6.png",
  ApiContract.url('${ApiContract.media.base}avatars/avatar_7.png'):
      "assets/images/avatar_7.png",
  ApiContract.url('${ApiContract.media.base}avatars/avatar_8.png'):
      "assets/images/avatar_8.png",
  ApiContract.url('${ApiContract.media.base}avatars/avatar_9.png'):
      "assets/images/avatar_9.png",
  ApiContract.url('${ApiContract.media.base}avatars/avatar_10.png'):
      "assets/images/avatar_10.png",
};
