import 'dart:convert';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:lingafriq/utils/transport_error_policy.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import '../../services/voice/audio_recording_service.dart';
import '../../services/polie_content_generator.dart';
import '../../widgets/voice/pronunciation_feedback_widget.dart';
import '../../providers/user_provider.dart';
import '../../providers/api_provider.dart';

/// Recording Prompt Model
class RecordingPrompt {
  final String id;
  final String text;
  final String translation;
  final String instructions;
  final String category;
  final String language;
  
  RecordingPrompt({
    required this.id,
    required this.text,
    required this.translation,
    required this.instructions,
    required this.category,
    required this.language,
  });
  
  Map<String, dynamic> toJson() => {
    'id': id,
    'text': text,
    'translation': translation,
    'instructions': instructions,
    'category': category,
    'language': language,
  };
  
  factory RecordingPrompt.fromJson(Map<String, dynamic> json) => RecordingPrompt(
    id: json['id'] ?? '',
    text: json['text'] ?? '',
    translation: json['translation'] ?? '',
    instructions: json['instructions'] ?? 'Speak naturally',
    category: json['category'] ?? 'words',
    language: json['language'] ?? '',
  );
}

/// Native Speaker Contribution Screen
/// 
/// Allows native speakers to contribute recordings for:
/// - Vocabulary pronunciation
/// - Sentence examples
/// - Correction phrases
/// - Cultural expressions
/// 
/// Prompts are dynamically generated by Polie AI.
/// All contributions help improve the app's voice features.
class NativeSpeakerContributionScreen extends ConsumerStatefulWidget {
  const NativeSpeakerContributionScreen({Key? key}) : super(key: key);

  @override
  ConsumerState<NativeSpeakerContributionScreen> createState() =>
      _NativeSpeakerContributionScreenState();
}

class _NativeSpeakerContributionScreenState
    extends ConsumerState<NativeSpeakerContributionScreen> {
  final AudioRecordingService _recorder = AudioRecordingService();
  
  String _selectedLanguage = 'Yoruba';
  String _selectedCategory = 'words';
  int _currentPromptIndex = 0;
  bool _isRecording = false;
  String? _lastRecordingPath;
  bool _hasConsented = false;
  int _recordingsCompleted = 0;
  bool _isLoadingPrompts = false;
  String? _loadError;
  
  // Dynamically generated prompts from Polie
  List<RecordingPrompt> _prompts = [];
  
  // Supported languages
  final List<String> _supportedLanguages = [
    'Yoruba', 'Swahili', 'Hausa', 'Igbo', 'Zulu', 'Amharic', 'Twi', 'Shona'
  ];
  
  // Categories for recording
  final Map<String, String> _categories = {
    'words': 'Single Words',
    'phrases': 'Short Phrases',
    'sentences': 'Full Sentences',
    'corrections': 'Correction Phrases',
    'greetings': 'Greetings & Politeness',
    'proverbs': 'Proverbs & Sayings',
    'numbers': 'Numbers & Counting',
    'questions': 'Questions',
  };
  
  RecordingPrompt? get _currentPrompt =>
      _currentPromptIndex < _prompts.length 
          ? _prompts[_currentPromptIndex] 
          : null;

  @override
  void initState() {
    super.initState();
    _recorder.requestPermission();
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    
    return Scaffold(
      appBar: AppBar(
        title: const Text('Contribute Your Voice'),
        backgroundColor: isDark ? const Color(0xFF1F3527) : Theme.of(context).colorScheme.surface,
        foregroundColor: isDark ? Theme.of(context).colorScheme.onSurface : Theme.of(context).colorScheme.onSurface,
        elevation: 0,
        actions: [
          if (_recordingsCompleted > 0)
            Padding(
              padding: EdgeInsets.only(right: 8.w),
              child: Chip(
                label: Text('$_recordingsCompleted recorded'),
                backgroundColor: Colors.green.shade100,
              ),
            ),
        ],
      ),
      body: _hasConsented 
          ? _buildContributionInterface(isDark)
          : _buildConsentScreen(isDark),
    );
  }

  Widget _buildConsentScreen(bool isDark) {
    return SingleChildScrollView(
      padding: EdgeInsets.all(24.sp),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Center(
            child: Column(
              children: [
                Container(
                  padding: EdgeInsets.all(20.sp),
                  decoration: BoxDecoration(
                    color: Colors.blue.shade50,
                    shape: BoxShape.circle,
                  ),
                  child: Icon(
                    Icons.record_voice_over,
                    size: 48.sp,
                    color: Colors.blue,
                  ),
                ),
                SizedBox(height: 16.h),
                Text(
                  'Help Teach Your Language',
                  style: TextStyle(
                    fontSize: 24.sp,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                SizedBox(height: 8.h),
                Text(
                  'Your voice helps millions learn African languages',
                  style: TextStyle(
                    fontSize: 16.sp,
                    color: Colors.grey.shade600,
                  ),
                  textAlign: TextAlign.center,
                ),
              ],
            ),
          ),
          SizedBox(height: 32.h),
          
          // Benefits
          _buildInfoSection(
            'What you\'ll do',
            [
              'Read words and phrases in your native language',
              'Help learners hear authentic pronunciation',
              'Contribute to preserving African languages',
              'AI generates unlimited prompts for you to record',
            ],
            Icons.checklist,
            Colors.green,
          ),
          SizedBox(height: 16.h),
          
          _buildInfoSection(
            'What you\'ll get',
            [
              '⭐ Free premium features for contributors',
              '🏆 Recognition as a language ambassador',
              '📜 Certificate of contribution',
              '🎯 Track your impact on learners',
            ],
            Icons.card_giftcard,
            Colors.orange,
          ),
          SizedBox(height: 16.h),
          
          _buildInfoSection(
            'Your privacy',
            [
              'Recordings used only for language learning',
              'No biometric identification',
              'You can delete your recordings anytime',
              'Licensed under Creative Commons (CC-BY)',
            ],
            Icons.security,
            Colors.blue,
          ),
          SizedBox(height: 32.h),
          
          // Consent checkbox
          CheckboxListTile(
            value: _hasConsented,
            onChanged: (value) {
              setState(() => _hasConsented = value ?? false);
            },
            title: Text(
              'I agree to contribute my voice recordings for language learning purposes under CC-BY license.',
              style: TextStyle(fontSize: 14.sp),
            ),
            controlAffinity: ListTileControlAffinity.leading,
          ),
          SizedBox(height: 16.h),
          
          // Start button
          SizedBox(
            width: double.infinity,
            child: ElevatedButton.icon(
              onPressed: _hasConsented ? () {
                _loadPrompts();
              } : null,
              icon: const Icon(Icons.mic),
              label: const Text('Start Contributing'),
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.green,
                foregroundColor: Theme.of(context).colorScheme.onPrimary,
                padding: EdgeInsets.symmetric(vertical: 16.h),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildInfoSection(String title, List<String> items, IconData icon, Color color) {
    return Container(
      padding: EdgeInsets.all(16.sp),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(icon, color: color, size: 24.sp),
              SizedBox(width: 8.w),
              Text(
                title,
                style: TextStyle(
                  fontSize: 16.sp,
                  fontWeight: FontWeight.bold,
                  color: color,
                ),
              ),
            ],
          ),
          SizedBox(height: 12.h),
          ...items.map((item) => Padding(
            padding: EdgeInsets.only(bottom: 8.h),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('• ', style: TextStyle(color: color)),
                Expanded(
                  child: Text(
                    item,
                    style: TextStyle(fontSize: 14.sp),
                  ),
                ),
              ],
            ),
          )),
        ],
      ),
    );
  }

  Widget _buildContributionInterface(bool isDark) {
    return Column(
      children: [
        // Language and category selector
        Container(
          padding: EdgeInsets.all(16.sp),
          decoration: BoxDecoration(
            color: isDark ? const Color(0xFF1F3527) : Theme.of(context).colorScheme.surface,
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.05),
                blurRadius: 10,
              ),
            ],
          ),
          child: Column(
            children: [
              // Language dropdown
              DropdownButtonFormField<String>(
                value: _selectedLanguage,
                decoration: InputDecoration(
                  labelText: 'Your Native Language',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                items: _supportedLanguages.map((lang) => DropdownMenuItem(
                  value: lang,
                  child: Text(lang),
                )).toList(),
                onChanged: (value) {
                  setState(() {
                    _selectedLanguage = value ?? _selectedLanguage;
                  });
                  _loadPrompts();
                },
              ),
              SizedBox(height: 12.h),
              
              // Category chips
              SingleChildScrollView(
                scrollDirection: Axis.horizontal,
                child: Row(
                  children: _categories.entries.map((entry) => Padding(
                    padding: EdgeInsets.only(right: 8.w),
                    child: _buildCategoryChip(entry.key, entry.value),
                  )).toList(),
                ),
              ),
            ],
          ),
        ),
        
        // Progress indicator
        if (_prompts.isNotEmpty)
          LinearProgressIndicator(
            value: (_currentPromptIndex + 1) / _prompts.length,
            backgroundColor: Colors.grey.shade200,
            color: Colors.green,
          ),
        
        // Main content
        Expanded(
          child: _isLoadingPrompts
              ? _buildLoadingState()
              : _loadError != null
                  ? _buildErrorState()
                  : _currentPrompt != null 
                      ? _buildPromptCard() 
                      : _prompts.isEmpty
                          ? _buildEmptyState()
                          : _buildCompletionCard(),
        ),
      ],
    );
  }

  Widget _buildCategoryChip(String value, String label) {
    final isSelected = _selectedCategory == value;
    return FilterChip(
      selected: isSelected,
      label: Text(label),
      onSelected: (selected) {
        setState(() {
          _selectedCategory = value;
          _currentPromptIndex = 0;
        });
        _loadPrompts();
      },
      selectedColor: Colors.green.shade100,
      checkmarkColor: Colors.green,
    );
  }

  Widget _buildLoadingState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          const CircularProgressIndicator(),
          SizedBox(height: 16.h),
          Text(
            'Polie is generating prompts...',
            style: TextStyle(
              fontSize: 16.sp,
              color: Colors.grey.shade600,
            ),
          ),
          SizedBox(height: 8.h),
          Text(
            'Creating authentic $_selectedLanguage content',
            style: TextStyle(
              fontSize: 14.sp,
              color: Colors.grey.shade500,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildErrorState() {
    return Center(
      child: Padding(
        padding: EdgeInsets.all(24.sp),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.error_outline,
              size: 64.sp,
              color: Colors.red.shade300,
            ),
            SizedBox(height: 16.h),
            Text(
              'Failed to load prompts',
              style: TextStyle(
                fontSize: 18.sp,
                fontWeight: FontWeight.bold,
              ),
            ),
            SizedBox(height: 8.h),
            Text(
              _loadError ?? 'Unknown error',
              style: TextStyle(
                fontSize: 14.sp,
                color: Colors.grey.shade600,
              ),
              textAlign: TextAlign.center,
            ),
            SizedBox(height: 24.h),
            ElevatedButton.icon(
              onPressed: _loadPrompts,
              icon: const Icon(Icons.refresh),
              label: const Text('Try Again'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Padding(
        padding: EdgeInsets.all(24.sp),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.mic_none,
              size: 64.sp,
              color: Colors.grey.shade400,
            ),
            SizedBox(height: 16.h),
            Text(
              'Ready to contribute!',
              style: TextStyle(
                fontSize: 18.sp,
                fontWeight: FontWeight.bold,
              ),
            ),
            SizedBox(height: 8.h),
            Text(
              'Select a category to start recording',
              style: TextStyle(
                fontSize: 14.sp,
                color: Colors.grey.shade600,
              ),
            ),
            SizedBox(height: 24.h),
            ElevatedButton.icon(
              onPressed: _loadPrompts,
              icon: const Icon(Icons.play_arrow),
              label: const Text('Generate Prompts'),
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.green,
                foregroundColor: Theme.of(context).colorScheme.onPrimary,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildPromptCard() {
    final prompt = _currentPrompt!;
    
    return Padding(
      padding: EdgeInsets.all(24.sp),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          // Progress text
          Text(
            '${_currentPromptIndex + 1} of ${_prompts.length}',
            style: TextStyle(
              fontSize: 14.sp,
              color: Colors.grey.shade600,
            ),
          ),
          SizedBox(height: 24.h),
          
          // Prompt card
          Card(
            elevation: 4,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(16),
            ),
            child: Padding(
              padding: EdgeInsets.all(24.sp),
              child: Column(
                children: [
                  // Native text (what to read)
                  Text(
                    prompt.text,
                    style: TextStyle(
                      fontSize: 28.sp,
                      fontWeight: FontWeight.bold,
                    ),
                    textAlign: TextAlign.center,
                  ),
                  SizedBox(height: 16.h),
                  
                  // Translation
                  Text(
                    prompt.translation,
                    style: TextStyle(
                      fontSize: 18.sp,
                      color: Colors.grey.shade600,
                    ),
                    textAlign: TextAlign.center,
                  ),
                  SizedBox(height: 16.h),
                  
                  // Instructions
                  Container(
                    padding: EdgeInsets.all(12.sp),
                    decoration: BoxDecoration(
                      color: Colors.blue.shade50,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Icon(Icons.info_outline, 
                             color: Colors.blue, 
                             size: 20.sp),
                        SizedBox(width: 8.w),
                        Flexible(
                          child: Text(
                            prompt.instructions,
                            style: TextStyle(
                              fontSize: 14.sp,
                              color: Colors.blue.shade700,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
          SizedBox(height: 32.h),
          
          // Recording button
          RecordingButton(
            isRecording: _isRecording,
            onPressed: _toggleRecording,
            amplitudeStream: _recorder.amplitudeStream,
          ),
          SizedBox(height: 16.h),
          
          Text(
            _isRecording ? 'Tap to stop' : 'Tap to record',
            style: TextStyle(
              fontSize: 14.sp,
              color: Colors.grey.shade600,
            ),
          ),
          
          // Last recording actions
          if (_lastRecordingPath != null) ...[
            SizedBox(height: 24.h),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                TextButton.icon(
                  onPressed: _reRecord,
                  icon: const Icon(Icons.refresh),
                  label: const Text('Re-record'),
                ),
                SizedBox(width: 16.w),
                ElevatedButton.icon(
                  onPressed: _submitAndNext,
                  icon: const Icon(Icons.check),
                  label: const Text('Submit & Next'),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.green,
                    foregroundColor: Theme.of(context).colorScheme.onPrimary,
                  ),
                ),
              ],
            ),
          ],
          
          // Skip button
          if (_lastRecordingPath == null)
            TextButton(
              onPressed: _skipPrompt,
              child: const Text('Skip this one'),
            ),
        ],
      ),
    );
  }

  Widget _buildCompletionCard() {
    return Center(
      child: Padding(
        padding: EdgeInsets.all(24.sp),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.celebration,
              size: 80.sp,
              color: Colors.amber,
            ),
            SizedBox(height: 24.h),
            Text(
              'Amazing Work! 🎉',
              style: TextStyle(
                fontSize: 28.sp,
                fontWeight: FontWeight.bold,
              ),
            ),
            SizedBox(height: 16.h),
            Text(
              'You\'ve completed all ${_categories[_selectedCategory]} prompts!',
              style: TextStyle(
                fontSize: 16.sp,
                color: Colors.grey.shade600,
              ),
              textAlign: TextAlign.center,
            ),
            SizedBox(height: 8.h),
            Text(
              'Total recordings this session: $_recordingsCompleted',
              style: TextStyle(
                fontSize: 18.sp,
                fontWeight: FontWeight.bold,
                color: Colors.green,
              ),
            ),
            SizedBox(height: 32.h),
            
            // Options
            ElevatedButton.icon(
              onPressed: () {
                _loadPrompts(); // Generate more prompts
              },
              icon: const Icon(Icons.add),
              label: const Text('Generate More Prompts'),
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.blue,
                foregroundColor: Theme.of(context).colorScheme.onPrimary,
                padding: EdgeInsets.symmetric(
                  horizontal: 24.w,
                  vertical: 16.h,
                ),
              ),
            ),
            SizedBox(height: 16.h),
            OutlinedButton.icon(
              onPressed: () {
                // Switch to next category
                final categories = _categories.keys.toList();
                final currentIdx = categories.indexOf(_selectedCategory);
                final nextIdx = (currentIdx + 1) % categories.length;
                setState(() {
                  _selectedCategory = categories[nextIdx];
                  _currentPromptIndex = 0;
                });
                _loadPrompts();
              },
              icon: const Icon(Icons.arrow_forward),
              label: const Text('Try Another Category'),
            ),
            SizedBox(height: 16.h),
            TextButton(
              onPressed: () => Navigator.of(context).pop(),
              child: const Text('Done for now'),
            ),
          ],
        ),
      ),
    );
  }

  /// Load prompts from Polie AI
  Future<void> _loadPrompts() async {
    setState(() {
      _isLoadingPrompts = true;
      _loadError = null;
      _currentPromptIndex = 0;
    });
    
    try {
      final polieGenerator = ref.read(polieContentGeneratorProvider);
      
      // Generate prompts based on category
      final prompts = await _generatePromptsForCategory(
        polieGenerator,
        _selectedLanguage,
        _selectedCategory,
      );
      
      setState(() {
        _prompts = prompts;
        _isLoadingPrompts = false;
      });
    } catch (e) {
      setState(() {
        _isLoadingPrompts = false;
        _loadError = e is DioException
            ? TransportErrorPolicy.toUserMessage(e)
            : e.toString();
      });
    }
  }

  /// Generate prompts using Polie based on category
  Future<List<RecordingPrompt>> _generatePromptsForCategory(
    PolieContentGenerator generator,
    String language,
    String category,
  ) async {
    final prompts = <RecordingPrompt>[];
    final count = 10; // Generate 10 prompts at a time
    
    switch (category) {
      case 'words':
        final content = await generator.generateGameContent(
          gameType: 'vocabulary_recording',
          language: language,
          additionalContext: '''Generate $count common words in $language for native speaker recording.
For each word provide:
1. The word in $language with proper diacritics
2. English translation
3. Recording instruction (e.g., "Clear pronunciation", "Watch the tone")

Format as JSON array:
[{"text": "word", "translation": "meaning", "instructions": "tip"}]''',
        );
        prompts.addAll(_parsePromptsFromContent(content, language, category));
        break;
        
      case 'phrases':
        final content = await generator.generateGameContent(
          gameType: 'phrase_recording',
          language: language,
          additionalContext: '''Generate $count short phrases (2-4 words) in $language for native speaker recording.
Include greetings, common expressions, and daily phrases.
Format as JSON array:
[{"text": "phrase", "translation": "meaning", "instructions": "tip"}]''',
        );
        prompts.addAll(_parsePromptsFromContent(content, language, category));
        break;
        
      case 'sentences':
        final content = await generator.generateGameContent(
          gameType: 'sentence_recording',
          language: language,
          additionalContext: '''Generate $count complete sentences in $language for native speaker recording.
Include various sentence types: statements, questions, commands.
Format as JSON array:
[{"text": "sentence", "translation": "meaning", "instructions": "tip"}]''',
        );
        prompts.addAll(_parsePromptsFromContent(content, language, category));
        break;
        
      case 'corrections':
        final content = await generator.generateGameContent(
          gameType: 'correction_recording',
          language: language,
          additionalContext: '''Generate $count correction/feedback phrases in $language that a teacher would use.
Include: "Try again", "Almost correct", "Well done", "Listen carefully", etc.
Format as JSON array:
[{"text": "phrase", "translation": "meaning", "instructions": "tip"}]''',
        );
        prompts.addAll(_parsePromptsFromContent(content, language, category));
        break;
        
      case 'greetings':
        final greetings = await generator.generateGreetings(language);
        if (greetings['formal'] != null) {
          for (int i = 0; i < (greetings['formal'] as List).length && i < count; i++) {
            final greeting = greetings['formal'][i];
            prompts.add(RecordingPrompt(
              id: 'greeting_formal_$i',
              text: greeting['native']?.toString() ?? greeting['text']?.toString() ?? '',
              translation: greeting['translation']?.toString() ?? greeting['english']?.toString() ?? '',
              instructions: 'Formal greeting - respectful tone',
              category: category,
              language: language,
            ));
          }
        }
        break;
        
      case 'proverbs':
        for (int i = 0; i < count; i++) {
          final proverb = await generator.generateProverb(language);
          prompts.add(RecordingPrompt(
            id: 'proverb_$i',
            text: proverb['proverb']?.toString() ?? proverb['text']?.toString() ?? '',
            translation: proverb['translation']?.toString() ?? proverb['meaning']?.toString() ?? '',
            instructions: 'Traditional proverb - meaningful pause',
            category: category,
            language: language,
          ));
        }
        break;
        
      case 'numbers':
        final content = await generator.generateGameContent(
          gameType: 'number_recording',
          language: language,
          additionalContext: '''Generate numbers 1-$count in $language for native speaker recording.
Include: digit, word form, and counting context.
Format as JSON array:
[{"text": "number word", "translation": "1, 2, 3...", "instructions": "clear enumeration"}]''',
        );
        prompts.addAll(_parsePromptsFromContent(content, language, category));
        break;
        
      case 'questions':
        final content = await generator.generateGameContent(
          gameType: 'question_recording',
          language: language,
          additionalContext: '''Generate $count common questions in $language for native speaker recording.
Include: What, Where, When, Who, How, Why questions.
Format as JSON array:
[{"text": "question", "translation": "meaning", "instructions": "question intonation"}]''',
        );
        prompts.addAll(_parsePromptsFromContent(content, language, category));
        break;
    }
    
    // Ensure we have at least some prompts
    if (prompts.isEmpty) {
      prompts.addAll(_getFallbackPrompts(language, category));
    }
    
    return prompts;
  }

  /// Parse prompts from Polie-generated content
  List<RecordingPrompt> _parsePromptsFromContent(
    Map<String, dynamic> content,
    String language,
    String category,
  ) {
    final prompts = <RecordingPrompt>[];
    
    try {
      final contentStr = content['content']?.toString() ?? '';
      
      // Try to extract JSON array from content
      final jsonMatch = RegExp(r'\[[\s\S]*\]').firstMatch(contentStr);
      if (jsonMatch != null) {
        final jsonStr = jsonMatch.group(0)!;
        final List<dynamic> items = jsonDecode(jsonStr);
        
        for (int i = 0; i < items.length; i++) {
          final item = items[i] as Map<String, dynamic>;
          prompts.add(RecordingPrompt(
            id: '${category}_${DateTime.now().millisecondsSinceEpoch}_$i',
            text: item['text']?.toString() ?? '',
            translation: item['translation']?.toString() ?? '',
            instructions: item['instructions']?.toString() ?? 'Speak naturally',
            category: category,
            language: language,
          ));
        }
      }
    } catch (e) {
      debugPrint('Error parsing prompts: $e');
    }
    
    return prompts;
  }

  /// Fallback prompts if Polie fails
  List<RecordingPrompt> _getFallbackPrompts(String language, String category) {
    // Basic fallback prompts
    final fallbacks = <RecordingPrompt>[];
    
    final basicWords = ['Hello', 'Thank you', 'Yes', 'No', 'Please', 'Water', 'Food', 'House', 'Person', 'Good'];
    
    for (int i = 0; i < basicWords.length; i++) {
      fallbacks.add(RecordingPrompt(
        id: 'fallback_${category}_$i',
        text: basicWords[i], // Would be translated
        translation: basicWords[i],
        instructions: 'Speak clearly and naturally',
        category: category,
        language: language,
      ));
    }
    
    return fallbacks;
  }

  Future<void> _toggleRecording() async {
    if (_isRecording) {
      final path = await _recorder.stopRecording();
      setState(() {
        _isRecording = false;
        _lastRecordingPath = path;
      });
    } else {
      final path = await _recorder.startRecording();
      if (path != null) {
        setState(() {
          _isRecording = true;
          _lastRecordingPath = null;
        });
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Please grant microphone permission'),
            ),
          );
        }
      }
    }
  }

  void _reRecord() {
    if (_lastRecordingPath != null) {
      _recorder.deleteRecording(_lastRecordingPath!);
    }
    setState(() {
      _lastRecordingPath = null;
    });
  }

  void _skipPrompt() {
    setState(() {
      _currentPromptIndex++;
      _lastRecordingPath = null;
    });
  }

  Future<void> _submitAndNext() async {
    if (_lastRecordingPath == null || _currentPrompt == null) return;
    
    // Submit recording to backend
    try {
      final api = ref.read(apiProvider.notifier);
      final user = ref.read(userProvider);
      
      final success = await api.submitVoiceContribution(
        userId: user?.id.toString() ?? 'anonymous',
        promptId: _currentPrompt!.id,
        language: _selectedLanguage,
        category: _selectedCategory,
        promptText: _currentPrompt!.text,
        audioPath: _lastRecordingPath!,
      );
      
      if (success) {
        setState(() {
          _recordingsCompleted++;
          _currentPromptIndex++;
          _lastRecordingPath = null;
        });
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Failed to submit. Saved locally for later.'),
              backgroundColor: Colors.orange,
            ),
          );
          // Still advance to next prompt
          setState(() {
            _recordingsCompleted++;
            _currentPromptIndex++;
            _lastRecordingPath = null;
          });
        }
      }
    } catch (e) {
      debugPrint('Error submitting contribution: $e');
      // Advance anyway, will sync later
      setState(() {
        _recordingsCompleted++;
        _currentPromptIndex++;
        _lastRecordingPath = null;
      });
    }
    
    // Clean up old recording
    if (_lastRecordingPath != null) {
      await _recorder.deleteRecording(_lastRecordingPath!);
    }
  }

  @override
  void dispose() {
    _recorder.cancelRecording();
    super.dispose();
  }
}
