# -*- coding: utf-8 -*-
"""LANG_PACKS for SupportedLanguages not in original launch set."""

from __future__ import annotations

from typing import Any

_COMMON_TAGS = [
    "WordMatch", "SpeedRound", "PronunciationDuel", "ToneTrainer",
    "FlashcardSafari", "GreetingDiplomacy", "MarketBargaining",
    "FoodQuest", "Roleplay", "ProverbUnlocker",
]

EXTENDED_LANG_PACKS: dict[str, dict[str, Any]] = {
    "afrikaans": {
        "display": "Afrikaans",
        "words": [
            ("Goeie môre", "Good morning", "greeting", "", "Use in formal settings."),
            ("Hallo", "Hello", "greeting", "", "Casual greeting."),
            ("Dankie", "Thank you", "expression", "", ""),
            ("Asseblief", "Please", "expression", "", ""),
            ("My naam is", "My name is", "phrase", "", ""),
            ("Hoe gaan dit?", "How are you?", "phrase", "", ""),
            ("Goed", "Good / fine", "phrase", "", ""),
            ("Water", "Water", "noun", "", ""),
            ("Kos", "Food", "noun", "", ""),
            ("Geld", "Money", "noun", "", ""),
            ("Huis", "House", "noun", "", ""),
            ("Motor", "Car", "noun", "", ""),
            ("Waar is", "Where is", "phrase", "", ""),
            ("Ek wil", "I want", "phrase", "", ""),
            ("Hoeveel kos dit?", "How much does it cost?", "phrase", "", ""),
            ("Dit is duur", "It is expensive", "phrase", "", ""),
            ("Goedkoop", "Cheap", "adjective", "", ""),
            ("Mark", "Market", "noun", "", ""),
            ("Werk", "Work", "noun", "", ""),
            ("Kantoor", "Office", "noun", "", ""),
            ("Ek werk", "I work", "phrase", "", ""),
            ("Môre", "Tomorrow", "noun", "", ""),
            ("Gister", "Yesterday", "noun", "", ""),
            ("Ek het geëet", "I have eaten", "phrase", "", "Past perfect."),
            ("Ek dink", "I think", "phrase", "", ""),
            ("Ek stem saam", "I agree", "phrase", "", ""),
            ("Ek stem nie saam nie", "I disagree", "phrase", "", ""),
            ("Nuus", "News", "noun", "", ""),
            ("Kultuur", "Culture", "noun", "", ""),
            ("Gemeenskap", "Community", "noun", "", ""),
            ("Siekte", "Illness", "noun", "", ""),
            ("Medisyne", "Medicine", "noun", "", ""),
        ],
        "proverbs": [
            ("Die appel val nie ver van die boom nie", "The apple does not fall far from the tree", "Family resemblance."),
            ("Goedkoop is duurkoop", "Cheap is expensive", "Quality has a price."),
        ],
        "scenarios": {
            "GreetingDiplomacy": [
                ("Meeting neighbour", "Goeie môre! Hoe gaan dit?", "Morning greeting", ""),
                ("Shop entrance", "Hallo! Dankie vir jou hulp.", "Polite thanks", ""),
            ],
            "MarketBargaining": [
                ("Stall", "Hoeveel kos dit? Dit is duur.", "Price talk", ""),
                ("Close", "Goed, dankie. Tot later.", "Polite close", ""),
            ],
            "TaxiSurvival": [
                ("Fare", "Waar is die mark? Hoeveel?", "Directions + fare", ""),
            ],
            "RoleplayAdventure": [
                ("Work day", "My naam is. Ek werk hier.", "Intro at work", ""),
            ],
        },
        "units": [
            ("Groete", "Hello", [
                ("Morning", ["Goeie môre", "Hallo", "Hoe gaan dit?"], "Greet and ask after someone.", ""),
                ("Thanks", ["Dankie", "Asseblief", "Goed"], "Courtesy phrases.", ""),
                ("Intro", ["My naam is", "Ek wil leer", "Hoe gaan dit?"], "Introduce yourself.", ""),
            ]),
            ("Huis", "Home", [
                ("Family", ["Huis", "Water", "Kos"], "Home vocabulary.", ""),
                ("Talk", ["Goed", "Dankie", "Hallo"], "Simple chat.", ""),
                ("Close", ["Tot later", "Dankie", "Goed"], "Leave-taking.", ""),
            ]),
            ("Mark", "Shop", [
                ("Food", ["Kos", "Water", "Mark"], "Market basics.", ""),
                ("Price", ["Ek wil", "Hoeveel kos dit?", "Geld"], "Buying.", ""),
                ("Deal", ["Goed", "Dankie", "Goedkoop"], "Close a deal.", ""),
            ]),
            ("Pad", "Travel", [
                ("Go", ["Motor", "Waar is", "Huis"], "Directions.", ""),
                ("Fare", ["Hoeveel kos dit?", "Asseblief", "Dankie"], "Transport.", ""),
                ("Exit", ["Tot later", "Dankie", "Goed"], "Leave.", ""),
            ]),
            ("Wysheid", "Culture", [
                ("Life", ["Die appel val nie ver van die boom nie", "Gemeenskap"], "Proverbs.", ""),
                ("Talk", ["Ek dink", "Kultuur", "Dankie"], "Opinion + culture.", ""),
                ("Close", ["Goed", "Dankie", "Hallo"], "Wrap up.", ""),
            ]),
        ],
    },
    "amharic": {
        "display": "Amharic",
        "words": [
            ("ሰላም", "Hello / peace", "greeting", "", "Universal greeting."),
            ("ጤና ይስጥልኝ", "Good health to you", "greeting", "", "Formal."),
            ("አመሰግናለሁ", "Thank you", "expression", "", ""),
            ("እባክህ", "Please", "expression", "", ""),
            ("ስሜ", "My name is", "phrase", "", ""),
            ("እንደምን አለህ?", "How are you? (m)", "phrase", "", ""),
            ("ደህና ነኝ", "I am fine", "phrase", "", ""),
            ("ውሃ", "Water", "noun", "", ""),
            ("ምግብ", "Food", "noun", "", ""),
            ("ገንዘብ", "Money", "noun", "", ""),
            ("ቤት", "House", "noun", "", ""),
            ("መኪና", "Car", "noun", "", ""),
            ("የት ነው", "Where is", "phrase", "", ""),
            ("እፈልጋለሁ", "I want", "phrase", "", ""),
            ("ስንት ነው?", "How much?", "phrase", "", ""),
            ("ብዙ ነው", "It is expensive / a lot", "phrase", "", ""),
            ("ገበያ", "Market", "noun", "", ""),
            ("ስራ", "Work", "noun", "", ""),
            ("ቢሮ", "Office", "noun", "", ""),
            ("እሰራለሁ", "I work", "phrase", "", ""),
            ("ነገ", "Tomorrow", "noun", "", ""),
            ("ትላንት", "Yesterday", "noun", "", ""),
            ("በላሁ", "I ate", "phrase", "", ""),
            ("እመስላለሁ", "I think", "phrase", "", ""),
            ("እስማማለሁ", "I agree", "phrase", "", ""),
            ("አልስማምምም", "I disagree", "phrase", "", ""),
            ("ዜና", "News", "noun", "", ""),
            ("ባህል", "Culture", "noun", "", ""),
            ("ማህበረሰብ", "Community", "noun", "", ""),
        ],
        "proverbs": [
            ("የሰው ልጅ ለሰው ልጅ ይረዳ", "People help one another", "Community solidarity."),
            ("በጎ ልብ ይበልጣል", "A good heart grows", "Character matters."),
        ],
        "scenarios": {
            "GreetingDiplomacy": [
                ("Street", "ሰላም! እንደምን አለህ?", "Greeting", ""),
                ("Shop", "አመሰግናለሁ። እባክህ።", "Thanks", ""),
            ],
            "MarketBargaining": [
                ("Price", "ስንት ነው? ብዙ ነው።", "Bargain", ""),
            ],
            "RoleplayAdventure": [
                ("Work", "ስሜ። እዚህ እሰራለሁ።", "Work intro", ""),
            ],
        },
        "units": [
            ("ሰላም", "Greetings", [
                ("Hello", ["ሰላም", "ጤና ይስጥልኝ", "እንደምን አለህ?"], "Greet.", ""),
                ("Thanks", ["አመሰግናለሁ", "እባክህ", "ደህና ነኝ"], "Courtesy.", ""),
                ("Name", ["ስሜ", "እፈልጋለሁ", "ደህና ነኝ"], "Introduce.", ""),
            ]),
            ("ቤት", "Home", [
                ("Home", ["ቤት", "ውሃ", "ምግብ"], "Home words.", ""),
                ("Talk", ["ደህና", "አመሰግናለሁ", "ሰላም"], "Chat.", ""),
                ("Close", ["ደህና", "አመሰግናለሁ", "ሰላም"], "Goodbye.", ""),
            ]),
            ("ገበያ", "Market", [
                ("Food", ["ምግብ", "ውሃ", "ገበያ"], "Market.", ""),
                ("Price", ["እፈልጋለሁ", "ስንት ነው?", "ገንዘብ"], "Buy.", ""),
                ("Deal", ["ደህና", "አመሰግናለሁ", "ሰላም"], "Close.", ""),
            ]),
            ("መንገድ", "Travel", [
                ("Go", ["መኪና", "የት ነው", "ቤት"], "Travel.", ""),
                ("Fare", ["ስንት ነው?", "እባክህ", "አመሰግናለሁ"], "Fare.", ""),
                ("Exit", ["ደህና", "አመሰግናለሁ", "ሰላም"], "Leave.", ""),
            ]),
            ("ባህል", "Culture", [
                ("Wisdom", ["የሰው ልጅ ለሰው ልጅ ይረዳ", "ባህል"], "Culture.", ""),
                ("Talk", ["እመስላለሁ", "ባህል", "አመሰግናለሁ"], "Discuss.", ""),
                ("Close", ["ደህና", "አመሰግናለሁ", "ሰላም"], "End.", ""),
            ]),
        ],
    },
    "twi": {
        "display": "Twi",
        "words": [
            ("Maakye", "Good morning", "greeting", "", ""),
            ("Hɛloo", "Hello", "greeting", "", ""),
            ("Meda wo ase", "Thank you", "expression", "", ""),
            ("Mesrɛ wo", "Please", "expression", "", ""),
            ("Me din de", "My name is", "phrase", "", ""),
            ("Ɛte sɛn?", "How are you?", "phrase", "", ""),
            ("Me ho yɛ", "I am fine", "phrase", "", ""),
            ("Nsuo", "Water", "noun", "", ""),
            ("Aduane", "Food", "noun", "", ""),
            ("Sika", "Money", "noun", "", ""),
            ("Fie", "House", "noun", "", ""),
            ("Kaa", "Car", "noun", "", ""),
            ("Ɛhe?", "Where?", "phrase", "", ""),
            ("Mepɛ", "I want", "phrase", "", ""),
            ("Ɛyɛ sɛn?", "How much?", "phrase", "", ""),
            ("Ɛyɛ den", "It is expensive", "phrase", "", ""),
            ("Gua", "Market", "noun", "", ""),
            ("Adwuma", "Work", "noun", "", ""),
            ("Ofis", "Office", "noun", "", ""),
            ("Mɛdwuma", "I work", "phrase", "", ""),
            ("Ɔkyena", "Tomorrow", "noun", "", ""),
            ("Deda", "Yesterday", "noun", "", ""),
            ("Meadi", "I ate", "phrase", "", ""),
            ("Misusuw sɛ", "I think", "phrase", "", ""),
            ("Mepene so", "I agree", "phrase", "", ""),
            ("Mempene so", "I disagree", "phrase", "", ""),
            ("Nnwom", "News", "noun", "", ""),
            ("Amammerɛ", "Culture", "noun", "", ""),
            ("Asafo", "Community", "noun", "", ""),
        ],
        "proverbs": [
            ("Obi nnim obi ama", "Nobody knows who will help whom", "Humility."),
            ("Wisdom is like a baobab tree", "Wisdom is vast", "Respect elders."),
        ],
        "scenarios": {
            "GreetingDiplomacy": [
                ("Morning", "Maakye! Ɛte sɛn?", "Greet", ""),
            ],
            "MarketBargaining": [
                ("Price", "Ɛyɛ sɛn? Ɛyɛ den.", "Bargain", ""),
            ],
        },
        "units": [
            ("Akyiade", "Greetings", [
                ("Greet", ["Maakye", "Hɛloo", "Ɛte sɛn?"], "Greetings.", ""),
                ("Thanks", ["Meda wo ase", "Mesrɛ wo", "Me ho yɛ"], "Thanks.", ""),
                ("Intro", ["Me din de", "Mepɛ", "Me ho yɛ"], "Intro.", ""),
            ]),
            ("Fie", "Home", [
                ("Home", ["Fie", "Nsuo", "Aduane"], "Home.", ""),
                ("Talk", ["Me ho yɛ", "Meda wo ase", "Maakye"], "Chat.", ""),
                ("Close", ["Me ho yɛ", "Meda wo ase", "Maakye"], "Bye.", ""),
            ]),
            ("Gua", "Market", [
                ("Food", ["Aduane", "Nsuo", "Gua"], "Market.", ""),
                ("Price", ["Mepɛ", "Ɛyɛ sɛn?", "Sika"], "Buy.", ""),
                ("Deal", ["Me ho yɛ", "Meda wo ase", "Maakye"], "Deal.", ""),
            ]),
            ("Kɔ", "Travel", [
                ("Go", ["Kaa", "Ɛhe?", "Fie"], "Go.", ""),
                ("Fare", ["Ɛyɛ sɛn?", "Mesrɛ wo", "Meda wo ase"], "Fare.", ""),
                ("Exit", ["Me ho yɛ", "Meda wo ase", "Maakye"], "Exit.", ""),
            ]),
            ("Amammerɛ", "Culture", [
                ("Wisdom", ["Obi nnim obi ama", "Amammerɛ"], "Culture.", ""),
                ("Talk", ["Misusuw sɛ", "Amammerɛ", "Meda wo ase"], "Talk.", ""),
                ("Close", ["Me ho yɛ", "Meda wo ase", "Maakye"], "End.", ""),
            ]),
        ],
    },
    "somali": {
        "display": "Somali",
        "words": [
            ("Salaan", "Greetings", "greeting", "", ""),
            ("Nabad", "Peace / hello", "greeting", "", ""),
            ("Mahadsanid", "Thank you", "expression", "", ""),
            ("Fadlan", "Please", "expression", "", ""),
            ("Magacaygu waa", "My name is", "phrase", "", ""),
            ("Sidee tahay?", "How are you?", "phrase", "", ""),
            ("Waan fiicanahay", "I am fine", "phrase", "", ""),
            ("Biyo", "Water", "noun", "", ""),
            ("Cunto", "Food", "noun", "", ""),
            ("Lacag", "Money", "noun", "", ""),
            ("Guri", "House", "noun", "", ""),
            ("Baabuur", "Car", "noun", "", ""),
            ("Xaggee", "Where", "phrase", "", ""),
            ("Waan rabaa", "I want", "phrase", "", ""),
            ("Immisa ayey ku kacaysaa?", "How much?", "phrase", "", ""),
            ("Waa qaali", "It is expensive", "phrase", "", ""),
            ("Suuq", "Market", "noun", "", ""),
            ("Shaqo", "Work", "noun", "", ""),
            ("Xafiis", "Office", "noun", "", ""),
            ("Waan shaqeeyaa", "I work", "phrase", "", ""),
            ("Berri", "Tomorrow", "noun", "", ""),
            ("Shalay", "Yesterday", "noun", "", ""),
            ("Waan cunay", "I ate", "phrase", "", ""),
            ("Waxaan u maleynayaa", "I think", "phrase", "", ""),
            ("Waan ogolahay", "I agree", "phrase", "", ""),
            ("Ma ogola", "I disagree", "phrase", "", ""),
            ("War", "News", "noun", "", ""),
            ("Dhaqan", "Culture", "noun", "", ""),
            ("Bulsho", "Community", "noun", "", ""),
        ],
        "proverbs": [
            ("Nabad iyo caano", "Peace and milk", "Prosperity blessing."),
            ("Guri waa guri", "Home is home", "Belonging."),
        ],
        "scenarios": {
            "GreetingDiplomacy": [
                ("Meet", "Salaan! Sidee tahay?", "Greet", ""),
            ],
            "MarketBargaining": [
                ("Price", "Immisa ayey ku kacaysaa?", "Price", ""),
            ],
        },
        "units": [
            ("Salaan", "Greetings", [
                ("Hi", ["Salaan", "Nabad", "Sidee tahay?"], "Greet.", ""),
                ("Thanks", ["Mahadsanid", "Fadlan", "Waan fiicanahay"], "Thanks.", ""),
                ("Intro", ["Magacaygu waa", "Waan rabaa", "Waan fiicanahay"], "Intro.", ""),
            ]),
            ("Guri", "Home", [
                ("Home", ["Guri", "Biyo", "Cunto"], "Home.", ""),
                ("Talk", ["Waan fiicanahay", "Mahadsanid", "Salaan"], "Chat.", ""),
                ("Close", ["Nabad", "Mahadsanid", "Salaan"], "Bye.", ""),
            ]),
            ("Suuq", "Market", [
                ("Food", ["Cunto", "Biyo", "Suuq"], "Market.", ""),
                ("Price", ["Waan rabaa", "Immisa ayey ku kacaysaa?", "Lacag"], "Buy.", ""),
                ("Deal", ["Waan fiicanahay", "Mahadsanid", "Nabad"], "Deal.", ""),
            ]),
            ("Safar", "Travel", [
                ("Go", ["Baabuur", "Xaggee", "Guri"], "Travel.", ""),
                ("Fare", ["Immisa ayey ku kacaysaa?", "Fadlan", "Mahadsanid"], "Fare.", ""),
                ("Exit", ["Nabad", "Mahadsanid", "Salaan"], "Exit.", ""),
            ]),
            ("Dhaqan", "Culture", [
                ("Wisdom", ["Nabad iyo caano", "Dhaqan"], "Culture.", ""),
                ("Talk", ["Waxaan u maleynayaa", "Dhaqan", "Mahadsanid"], "Talk.", ""),
                ("Close", ["Nabad", "Mahadsanid", "Salaan"], "End.", ""),
            ]),
        ],
    },
    "lingala": {
        "display": "Lingala",
        "words": [
            ("Mbote", "Hello", "greeting", "", ""),
            ("Matondi", "Thank you", "expression", "", ""),
            ("Svp", "Please", "expression", "", ""),
            ("Nkombo na ngai", "My name is", "phrase", "", ""),
            ("Boni?", "How are you?", "phrase", "", ""),
            ("Malamu", "Good / fine", "phrase", "", ""),
            ("Mai", "Water", "noun", "", ""),
            ("Bilei", "Food", "noun", "", ""),
            ("Mbongo", "Money", "noun", "", ""),
            ("Ndako", "House", "noun", "", ""),
            ("Moto", "Car", "noun", "", ""),
            ("Wapi", "Where", "phrase", "", ""),
            ("Nalingi", "I want", "phrase", "", ""),
            ("Nini?", "How much?", "phrase", "", ""),
            ("Ezali monene", "It is expensive", "phrase", "", ""),
            ("Zando", "Market", "noun", "", ""),
            ("Mosala", "Work", "noun", "", ""),
            ("Bureau", "Office", "noun", "", ""),
            ("Nasalaka", "I work", "phrase", "", ""),
            ("Lobi", "Tomorrow", "noun", "", ""),
            ("Lobi eleki", "Yesterday", "noun", "", ""),
            ("Malaki", "I ate", "phrase", "", ""),
            ("Nakanisi ete", "I think", "phrase", "", ""),
            ("Nandimi", "I agree", "phrase", "", ""),
            ("Nandimi te", "I disagree", "phrase", "", ""),
            ("Sango", "News", "noun", "", ""),
            ("Bizaleli", "Culture", "noun", "", ""),
            ("Lisanga", "Community", "noun", "", ""),
        ],
        "proverbs": [
            ("Mobembo moko ezali te", "There is no journey alone", "Community."),
        ],
        "scenarios": {
            "GreetingDiplomacy": [("Street", "Mbote! Boni?", "Greet", "")],
            "MarketBargaining": [("Price", "Nini? Ezali monene.", "Price", "")],
        },
        "units": [
            ("Mbote", "Hello", [
                ("Hi", ["Mbote", "Boni?", "Malamu"], "Greet.", ""),
                ("Thanks", ["Matondi", "Svp", "Malamu"], "Thanks.", ""),
                ("Intro", ["Nkombo na ngai", "Nalingi", "Malamu"], "Intro.", ""),
            ]),
            ("Ndako", "Home", [
                ("Home", ["Ndako", "Mai", "Bilei"], "Home.", ""),
                ("Talk", ["Malamu", "Matondi", "Mbote"], "Chat.", ""),
                ("Close", ["Malamu", "Matondi", "Mbote"], "Bye.", ""),
            ]),
        ],
    },
    "shona": {
        "display": "Shona",
        "words": [
            ("Mangwanani", "Good morning", "greeting", "", ""),
            ("Mhoro", "Hello", "greeting", "", ""),
            ("Ndatenda", "Thank you", "expression", "", ""),
            ("Ndapota", "Please", "expression", "", ""),
            ("Zita rangu ndini", "My name is", "phrase", "", ""),
            ("Makadii?", "How are you?", "phrase", "", ""),
            ("Ndiri zvakanaka", "I am fine", "phrase", "", ""),
            ("Mvura", "Water", "noun", "", ""),
            ("Chikafu", "Food", "noun", "", ""),
            ("Mari", "Money", "noun", "", ""),
            ("Imba", "House", "noun", "", ""),
            ("Mota", "Car", "noun", "", ""),
            ("Kupi?", "Where?", "phrase", "", ""),
            ("Ndinoda", "I want", "phrase", "", ""),
            ("Zvakadini?", "How much?", "phrase", "", ""),
            ("Zvakadaro", "It is expensive", "phrase", "", ""),
            ("Musika", "Market", "noun", "", ""),
            ("Basa", "Work", "noun", "", ""),
            ("Ophisi", "Office", "noun", "", ""),
            ("Ndinoshanda", "I work", "phrase", "", ""),
            ("Mangwana", "Tomorrow", "noun", "", ""),
            ("Nezuro", "Yesterday", "noun", "", ""),
            ("Ndadya", "I ate", "phrase", "", ""),
            ("Ndinofunga", "I think", "phrase", "", ""),
            ("Ndinobvuma", "I agree", "phrase", "", ""),
            ("Handibvumi", "I disagree", "phrase", "", ""),
            ("Nhau", "News", "noun", "", ""),
            ("Tsika", "Culture", "noun", "", ""),
            ("Nharaunda", "Community", "noun", "", ""),
        ],
        "proverbs": [
            ("Chara chimwe hachitswanyi inda", "One finger cannot crush a louse", "Unity."),
        ],
        "scenarios": {
            "GreetingDiplomacy": [("Meet", "Mhoro! Makadii?", "Greet", "")],
            "MarketBargaining": [("Price", "Zvakadini?", "Price", "")],
        },
        "units": [
            ("Mhoro", "Greetings", [
                ("Hi", ["Mangwanani", "Mhoro", "Makadii?"], "Greet.", ""),
                ("Thanks", ["Ndatenda", "Ndapota", "Ndiri zvakanaka"], "Thanks.", ""),
                ("Intro", ["Zita rangu ndini", "Ndinoda", "Ndiri zvakanaka"], "Intro.", ""),
            ]),
            ("Imba", "Home", [
                ("Home", ["Imba", "Mvura", "Chikafu"], "Home.", ""),
                ("Talk", ["Ndiri zvakanaka", "Ndatenda", "Mhoro"], "Chat.", ""),
                ("Close", ["Ndiri zvakanaka", "Ndatenda", "Mhoro"], "Bye.", ""),
            ]),
        ],
    },
}
